name: Deploy Ingestion ADF
run-name: Deploy Ingestion ADF

on:
  workflow_dispatch: 
  pull_request:
    types: [closed]
    branches: [test]
  # push:
  #   branches:
  #     - Development
    
jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0  
        
      - name: Export ARM templates
        id: export
        uses: Azure/data-factory-export-action@v1.2.0
        with:
          path: Ingestion
#           id: /subscriptions/14408b8c-b4a0-4817-8fbc-31a52b9b9399/resourceGroups/CI-CD/providers/Microsoft.DataFactory/factories/dev-mvc-adf

      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error

  deploy_to_uat_ingestion_adf:
    # if: ${{ github.ref == 'refs/heads/uat' || github.ref_name == 'uat' }}
    needs: [build_ARM_templates]
    name: Deploy to TEST ADF
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Login to Azure
        uses: azure/login@v1.4.6
        with:
          creds: '{"clientId": "783b2059-b713-43c6-b86f-f670de79ae0f","clientSecret": "M328Q~WUFNZSHyMX8VckkoXQ3QUI34ZJfiVtGcjg","subscriptionId": "2bcf5e1a-2a28-4ce2-8082-e04bec437ea0","tenantId": "c12aba17-76aa-43ae-a98e-54302f617a40"}'
          enable-AzPSSession: true
          # allow-no-subscriptions: true

      - name: Download ARM templates artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: armtemplates
          path: armtemplates

      - name: Deploy to TEST
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: mvc-cicd #${{ secrets.TEST_INGESTION_ADF_RESOURCE_GROUP_NAME}}
          dataFactoryName: tst-mvc-adf #${{ secrets.TEST_INGESTION_DATA_FACTORY_NAME}}
          armTemplateFile: ./armtemplates/ARMTemplateForFactory.json
          armTemplateParametersFile: ./TEST-ARMTemplateParametersForFactory.json
          failOnStdErr: false

################### End of workflow file ###################
